### ISSUE TITLE
KeyError: 'directories'

### ISSUE THREAD

**Issue by aasutossh** [InspectorMustache/maninex#2]
Hello, I am on Manjaro XFCE 17.1, I had used maninex previously as a script,
now I installed it using pip, but when I enter `maninex --print-skel` i get the following error.
`maninex --print-skel`
`Traceback (most recent call last):`
 ` File "/usr/bin/maninex", line 7, in <module>`
`    from maninex import main`
 ` File "/usr/lib/python3.6/site-packages/maninex/__init__.py", line 1, in <module>`
`    from .maninex import main`
`  File "/usr/lib/python3.6/site-packages/maninex/maninex.py", line 397, in <module>`
`    json_dir = get_real_path(config['directories']['json_dir'])`
`  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__`
`    raise KeyError(key)`
`KeyError: 'directories'``

**Comment by RealFerdinandDeSaussure** [comment]
Yes, `--print-skel` doesn't work if there isn't a valid config file already present, which of course makes no sense. I probably should have bothered writing real tests so things like this don't happen. Anyway, it should be fixed now. Can you do `pip install -U maninex` and report back if everything's working for you?

**Comment by aasutossh** [comment]
I had exams so I couldn't be able to reply but the problem still persists.
`maninex -s`
`Traceback (most recent call last):`
`  File "/usr/bin/maninex", line 11, in <module>`
`    sys.exit(main())`
`  File "/usr/lib/python3.6/site-packages/maninex/maninex.py", line 406, in main`
`    scan_mode()`
`  File "/usr/lib/python3.6/site-packages/maninex/maninex.py", line 321, in scan_mode`
`    config_struct = get_config()`
`  File "/usr/lib/python3.6/site-packages/maninex/maninex.py", line 381, in get_config`
`    json_dir = get_real_path(config['directories']['json_dir'])`
`  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__`
`    raise KeyError(key)`
`KeyError: 'directories'`

**Comment by RealFerdinandDeSaussure** [comment]
Strange, I'll look into it.

**Comment by RealFerdinandDeSaussure** [comment]
Okay, this is probably because your config file isn't properly formatted. It's either missing the `[directories]` header or a line specifying json_dir. Of course, it would be nicer if there was a proper error message that pointed the user in that direction. I'll get onto that.

**Comment by aasutossh** [comment]
Sure.

**Comment by RealFerdinandDeSaussure** [comment]
Awesome. So that means it works for you once you fix your config file or what?

**Comment by aasutossh** [comment]
Yeah it was my bad.
 `maninex --print-skel > ~/.config/maninex.conf` fixed the **Directory** Problem.

**Comment by RealFerdinandDeSaussure** [comment]
Okay, that's good to hear. I pushed an update printing an appropriate error message to the PyPI.
